export const customEvmNetworks = [
  {
    blockExplorerUrls: ["https://filfox.info/en"],
    chainId: 314,
    name: "Filecoin",
    rpcUrls: ["https://api.node.glif.io/rpc/v1"],
    iconUrls: ["https://avatars.githubusercontent.com/u/22014611?s=200&v=4"],
    nativeCurrency: {
      name: "Filecoin",
      symbol: "FIL",
      decimals: 18,
    },
    networkId: 314,
  },
  {
    blockExplorerUrls: ["https://calibration.filfox.info/en"],
    chainId: 314159,
    name: "Filecoin Calibration",
    rpcUrls: ["https://api.calibration.node.glif.io/rpc/v1"],
    iconUrls: ["https://avatars.githubusercontent.com/u/22014611?s=200&v=4"],
    nativeCurrency: {
      name: "Filecoin",
      symbol: "FIL",
      decimals: 18,
    },
    networkId: 314159,
  },
  {
    blockExplorerUrls: ["https://explorer-holesky.morphl2.io/"],
    chainId: 2810,
    name: "Morph",
    rpcUrls: ["https://rpc-quicknode-holesky.morphl2.io"],
    iconUrls: ["https://avatars.githubusercontent.com/u/132543920?v=4"],
    nativeCurrency: {
      name: "Ethereum",
      symbol: "ETH",
      decimals: 18,
    },
    networkId: 2810,
  },
  {
    blockExplorerUrls: ["https://explorer.zircuit.com"],
    chainId: 48899,
    name: "Zircuit Testnet",
    rpcUrls: ["https://zircuit1.p2pify.com/"],
    iconUrls: ["https://pbs.twimg.com/profile_images/1774812048683143168/gSbmfQfa_400x400.jpg"],
    nativeCurrency: {
      name: "Ethereum",
      symbol: "ETH",
      decimals: 18,
    },
    networkId: 48899,
  },
  {
    blockExplorerUrls: ["https://explorer.zero.network"],
    chainId: 4457845,
    name: "ZERϴ",
    rpcUrls: ["https://rpc.zerion.io/v1/zero-sepolia"],
    iconUrls: ["https://pbs.twimg.com/profile_images/1805906049213329408/oZFUGW9L_400x400.jpg"],
    nativeCurrency: {
      name: "Ethereum",
      symbol: "ETH",
      decimals: 18,
    },
    networkId: 4457845,
  },
  {
    blockExplorerUrls: ["https://explorer.testnet.rsk.co"],
    chainId: 31,
    name: "RSK Testnet",
    rpcUrls: ["https://public-node.testnet.rsk.co"],
    iconUrls: ["https://rootstock.io/icons/icon-512x512.png?v=d5199ca8e8f274bc01b19fe9024f128e"],
    nativeCurrency: {
      name: "Rootstock Bitcoin",
      symbol: "tRBTC",
      decimals: 18,
    },
    networkId: 31,
  },
  {
    blockExplorerUrls: ["https://explorer.rsk.co"],
    chainId: 30,
    name: "RSK Mainnet",
    rpcUrls: ["https://public-node.rsk.co"],
    iconUrls: ["https://rootstock.io/icons/icon-512x512.png?v=d5199ca8e8f274bc01b19fe9024f128e"],
    nativeCurrency: {
      name: "Rootstock Bitcoin",
      symbol: "tRBTC",
      decimals: 18,
    },
    networkId: 30,
  },
];
